language: python
python:
  - "2.7"
  - "3.5"
env:
  - DJANGO="Django>=1.7,<1.8"
  - DJANGO="Django>=1.8,<1.9"
  - DJANGO="Django>=1.9,<1.10"
  - DJANGO="Django>=1.10,<1.11"
  - DJANGO="Django>=1.11,<2.0"
  - DJANGO="Django>=2.0,<2.1"
  - DJANGO='https://github.com/django/django/archive/master.tar.gz'
# command to install dependencies
install:
  - pip install $DJANGO
  - pip install -q -e .
  - pip install -r requirements.txt
# command to run tests
script:
  - coverage run --source=massadmin manage.py test --settings=tests.settings
after_success:
  coveralls
matrix:
  allow_failures:
     - env: DJANGO='https://github.com/django/django/archive/master.tar.gz'
  exclude:
    - python: "3.5"
      env: DJANGO="Django>=1.7,<1.8"
    - python: "2.7"
      env: DJANGO="Django>=2.0,<2.1"
    - python: "2.7"
      env: DJANGO='https://github.com/django/django/archive/master.tar.gz'
