language: python
python:
  - "2.7"
  - "3.4"
env:
  - DJANGO="Django>=1.6,<1.7"
  - DJANGO="Django>=1.7,<1.8"
  - DJANGO="Django>=1.8,<1.9"
  - DJANGO="Django>=1.9,<1.10"
  - DJANGO='https://github.com/django/django/archive/master.tar.gz'
# command to install dependencies
install:
  - pip install $DJANGO --use-mirrors
  - pip install -q -e . --use-mirrors
  - pip install -r requirements.txt
# command to run tests
script:
  - coverage run --source=massadmin manage.py test --settings=tests.settings
after_success:
  coveralls
sudo: false
matrix:
  allow_failures:
     - env: DJANGO='https://github.com/django/django/archive/master.tar.gz'
